---
- name: Flatpak | Add Flathub remote
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system 
    
- name: Flatpak | Install Flatpaks
  become: true
  flatpak:
    name: "{{ item }}"  
    remote: flathub
    method: system
    state: present
  with_items:
    - "{{ flatpakpkg }}"  